from remind_mfa.common.common_mappings import CommonDimensionFiles, CommonDisplayNames


class PlasticsDisplayNames(CommonDisplayNames):
    _own_mapping = {
        "sysenv": "System environment",
        "feedfoss": "Feedstock(fossil)",
        "feedbio": "Feedstock(biomass)",
        "feeddaccu": "Feedstock(daccu)",
        "feedccu": "Feedstock(ccu)",
        "HVC_input": "High Value Chemical input",
        "C4_input": "C4 input",
        "other_reactants": "Other Reactants",
        "polymerization": "Polymerization",
        "losses": "Losses",
        "processing": "Processing",
        "manufacturing": "Manufacturing",
        "reclmech": "Mechanical Recycling",
        "reclchem": "Chemical Recycling",
        "use": "Use Phase",
        "eol": "EoL",
        "collected": "Collected",
        "mismanaged": "Uncollected",
        "incineration": "Incineration",
        "landfill": "Landfilled",
        "uncontrolled": "Uncontrolled",
        "emission": "Emissions",
        "captured": "Captured",
        "atmosphere": "Atmosphere",
        "waste_market": "Waste Market",
        "primary_market": "Primary Market",
        "manufactured_products_market": "Manufactured Products Market",
        "imports": "Imports",
        "exports": "Exports",
        "aux_recyclate": "Auxiliary Recyclate Trade",
        "aux_recl_feedstock": "Auxiliary Recycled Feedstock Trade",
    }
