[base]
    [base.input]
        force_extract_tgz = false
        input_data_path = "../remind_mfa_data"
        input_data_revision = "1.6.1"
        region_mapping = "h12"
        scenarios_path = "config/scenarios"

    [base.model_switches]
        scenario = "SSP2"
        stock_extrapolation_class_name = "LogisticExtrapolation"
        regress_over = "loggdppc"
        lifetime_model_name = "LogNormalLifetime"
        do_stock_extrapolation_by_category = false
        do_stock_extrapolation_with_time_factor = false

    [base.visualization]
        do_visualize = true
        do_show_figs = true
        do_save_figs = false
        plotting_engine = "plotly"
        use_stock.do_visualize = true
        use_stock.over_gdp = true
        use_stock.per_capita = true
        use_stock.accumulate_gdp = false
        gdp.do_visualize = false
        gdp.per_capita = false
        production.do_visualize = false
        trade.do_visualize = false
        consumption.do_visualize = false
        consumption.per_capita = false
        sankey.do_visualize = false
        sankey.plotter_args.slice_dict = { "t" = 2050 }
        sankey.plotter_args.exclude_processes = ["sysenv"]
        sankey.plotter_args.exclude_flows = []
        extrapolation.do_visualize = true
        sector_splits.do_visualize = false

    [base.export]
        do_export = true
        pickle.do_export = true
        csv.do_export = false
        iamc.do_export = false
        mrindustry.do_export = true
        assumptions.do_export = false
        docs.do_export = false

[plastics]
    [plastics.model_switches]
        do_stock_extrapolation_by_category = true
        do_stock_extrapolation_with_time_factor = true

    [plastics.visualization]
        figures_path = "data/plastics/output/figures"
        consumption.do_visualize = true
        consumption.per_capita = true
        trade.do_visualize = true
        sankey.do_visualize = true
        sankey.plotter_args.slice_dict = { "t" = 2050, "e" = "C" }
        sector_splits.do_visualize = true
        material_splits.do_visualize = true
        flows.do_visualize = false

    [plastics.export]
        do_export = false
        path = "data/plastics/output/export"
        csv.do_export = true
        iamc.do_export = true
        assumptions.do_export = true
        docs.do_export = true
        docs.path = "docs/plastics"

[steel]
    [steel.model_switches]
        do_stock_extrapolation_by_category = true

    [steel.visualization]
        figures_path = "data/steel/output/figures"
        production.do_visualize = true
        scrap_demand_supply.do_visualize = false

    [steel.export]
        path = "data/steel/output/export"
        docs.path = "docs/steel"

[cement]
    [cement.model_switches]
        carbonation = false
        parameter_reconciliation.do_reconcile = false
        parameter_reconciliation.do_combine_mfas = true
        do_stock_extrapolation_by_category = false

    [cement.visualization]
        figures_path = "data/cement/output/figures"
        trade.do_visualize = true
        consumption.do_visualize = true
        eol_stock.do_visualize = false
        eol_stock.over_gdp = false
        eol_stock.per_capita = false
        prod_clinker.do_visualize = false
        prod_cement.do_visualize = true
        prod_product.do_visualize = false
        sankey.plotter_args.split_flows_by = "Stock Type"
        sankey.plotter_args.color_scheme = "blueish"
        sankey.plotter_args.flow_color = "hsl(230,20,70)"
        carbonation.do_visualize = true

    [cement.export]
        path = "data/cement/output/export"
        docs.path = "docs/cement"
        pickle.do_export = false
