[base]
    [base.input]
        force_extract_tgz = false
        input_data_path = "../remind_mfa_data"
        input_data_revision = "1.6.1"
        region_mapping = "h12"
        scenarios_path = "config/scenarios"

    [base.model_switches]
        scenario = "SSP2"
        stock_extrapolation_class_name = "LogisticExtrapolation"
        regress_over = "loggdppc"
        lifetime_model_name = "LogNormalLifetime"
        do_stock_extrapolation_by_category = false
        do_stock_extrapolation_with_time_factor = false

    [base.transience]
        transience_run = true
        
    [base.visualization]
        do_visualize = true
        do_show_figs = true
        do_save_figs = false
        plotting_engine = "plotly"
        use_stock.do_visualize = true
        use_stock.over_gdp = true
        use_stock.per_capita = true
        use_stock.accumulate_gdp = false
        gdp.do_visualize = false
        gdp.per_capita = false
        production.do_visualize = true
        trade.do_visualize = false
        consumption.do_visualize = true
        consumption.per_capita = true
        sankey.do_visualize = false
        sankey.plotter_args.slice_dict = { "t" = 2050 }
        sankey.plotter_args.exclude_processes = ["sysenv"]
        sankey.plotter_args.exclude_flows = []
        extrapolation.do_visualize = true
        sector_splits.do_visualize = false

    [base.export]
        do_export = true
        pickle.do_export = true
        csv.do_export = false
        iamc.do_export = false
        mrindustry.do_export = false
        assumptions.do_export = false
        docs.do_export = false

[plastics]
    [plastics.input]
        input_data_revision = '1.5.0fix_plWastePolymerSplit'
        region_mapping = '2c0a4149' # EU27+3 TRANSIENCE region mapping

    [plastics.model_switches]
        do_stock_extrapolation_by_category = true
        do_stock_extrapolation_with_time_factor = true

    [plastics.transience]
        baseline_pickle_path = 'model_plastics_SSP2_transience_CE-PET_fd_plastics_S0_default_2c0a4149_2026-06-29--09-13-07.pickle'
        transience_scenario = 'CE-PET_fd_plastics_S0' # 'CE-PET_fd_plastics_S0', 'CE-PET_fd_plastics_S1', 'CE-PET_fd_plastics_S2'
        trade_scenario = 'default' # 'default', 'fix_supply_alpha0' (export expansion), or 'fix_supply_alpha1' (import substitution)

    [plastics.visualization]
        figures_path = "data/plastics/output/transience/figures"
        sankey.plotter_args.slice_dict = { "t" = 2019, "r" = "EU27+3", "m" = "PET" }
        sankey.plotter_args.exclude_processes = ["sysenv", "atmosphere", "feedfoss", "feedbio", "feeddaccu", "feedccu", "HVC_input", "C4_input", "other_reactants", "emission", "uncontrolled", "incineration", "losses", "reclchem", "mismanaged", "landfill"]
        material_splits.do_visualize = true
        flows.do_visualize = false

    [plastics.export]
        path = "data/plastics/output/transience"
        docs.path = "docs/plastics"

[steel]
    [steel.model_switches]
        do_stock_extrapolation_by_category = true

    [steel.transience]
        baseline_pickle_path = 'model_steel_SSP2_transience_Baseline_Steel_01_06_2026_default_h12_2026-06-04--13-58-49.pickle'
        transience_scenario = 'Baseline_Steel_01_06_2026' # 'Baseline_Steel_01_06_2026', 'Downsizing_Conservative_Steel_01_06_2026', 'Downsizing_Highly_Ambitious_Steel_result_01_06_2026', 'Redesign_ Conservative_Steel', 'Redesign_ Highly_Ambitious_Steel', 'Remanufacturing_Conservative_Steel', 'Remanufacturing_Highly_Ambitious_Steel', 'Combined_Conservative_Steel', 'Combined_Highly_Ambitious_Steel'
        trade_scenario = 'default' # 'default', 'fix_supply_alpha0' (export expansion), or 'fix_supply_alpha1' (import substitution)

    [steel.visualization]
        figures_path = "data/steel/output/transience/figures"
        scrap_demand_supply.do_visualize = false

    [steel.export]
        path = "data/steel/output/transience"
        docs.path = "docs/steel"

[cement]
    [cement.model_switches]
        carbonation = false
        parameter_reconciliation.do_reconcile = false
        parameter_reconciliation.do_combine_mfas = true
        do_stock_extrapolation_by_category = false

    [cement.visualization]
        figures_path = "data/cement/output/figures"
        eol_stock.do_visualize = false
        eol_stock.over_gdp = false
        eol_stock.per_capita = false
        prod_clinker.do_visualize = false
        prod_cement.do_visualize = true
        prod_product.do_visualize = false
        sankey.plotter_args.split_flows_by = "Stock Type"
        sankey.plotter_args.color_scheme = "blueish"
        sankey.plotter_args.flow_color = "hsl(230,20,70)"
        carbonation.do_visualize = false

    [cement.export]
        path = "data/cement/output/export"
        docs.path = "docs/cement"
