model: 'steel'

input:
  force_extract_tgz: False
  scenarios_path: 'config/scenarios'
  input_data_path: '../remind_mfa_data/'
  input_data_revision: '1.5.0'
  region_mapping: 'h12'

model_switches:
  scenario: 'SSP2'
  # stock_extrapolation_class_name: 'TwoPredictorGompertzExtrapolation'
  # regress_over: loggdppc_time
  stock_extrapolation_class_name: 'LogisticExtrapolation'
  regress_over: loggdppc
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True

visualization:
  do_visualize: True
  do_show_figs: True
  do_save_figs: False
  figures_path: 'data/steel/output/figures'
  plotting_engine: 'plotly'
  extrapolation:
    do_visualize: True
  scrap_demand_supply:
    do_visualize: False
  sector_splits:
    do_visualize: False
  use_stock:
    do_visualize: True
    over_gdp: True
    per_capita: True
  gdppc:
    do_visualize: False
    per_capita: False
  production:
    do_visualize: True
  consumption:
    do_visualize: False
  trade:
    do_visualize: False
  sankey:
    do_visualize: False
    plotter_args:
      slice_dict:
        t: 2050
        # r: 'USA'
      exclude_processes:
        - "sysenv"
        #- "imports"
        #- "exports"
      exclude_flows: [ ]

export:
  do_export: True
  path: 'data/steel/output/export'
  pickle:
    do_export: True
  csv:
    do_export: False
  iamc:
    do_export: False
  assumptions:
    do_export: False
  docs:
    do_export: False
    path: 'docs/steel'
